# Generated by Django 2.2.2 on 2019-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_auto_20190809_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
