# Generated by Django 2.2.2 on 2019-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_ad_adding_cur_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_tag',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
