# Generated by Django 2.2.2 on 2019-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_auto_20190812_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_adding',
            name='cur_tag',
        ),
        migrations.DeleteModel(
            name='Currency_tag',
        ),
    ]
