# Generated by Django 2.2.2 on 2019-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0006_auto_20190812_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_adding',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
