# Generated by Django 2.2.2 on 2019-08-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_ad_adding_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_adding',
            name='image',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='ad_adding',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
