# Generated by Django 2.2.2 on 2019-08-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0008_auto_20190813_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_adding',
            name='image',
        ),
    ]
